### ISSUE TITLE
[Re] A Neurodynamical Model for Working Memory

### ISSUE THREAD

**Issue by theoboraud** [ReScience/submissions#8]
**Original article:** [A Neurodynamical Model for Working Memory](https://www.sciencedirect.com/science/article/abs/pii/S0893608010001899)

**PDF URL:** [\[Re\] A Neurodynamical Model for Working Memory](https://github.com/theoboraud/ESN/blob/master/ReScience%20Article/ReScience_Article.pdf)
**Metadata URL:** [Metadata.yaml](https://github.com/theoboraud/ESN/blob/master/ReScience%20Article/metadata.yaml)
**Code URL:** [Code repository](https://zenodo.org/record/3518002#.XbF8D5MzaL8)

**Scientific domain:** Computational Neuroscience
**Programming language:** Python
**Suggested editor:**

**Comment by rougier** [comment]
@benoit-girard Could you edit this submission?

**Comment by benoit-girard** [comment]
Yes !

Benoît Girard
ISIR - UPMC / CNRS
http://people.isir.upmc.fr/girard

----- Reply message -----
De : "Nicolas P. Rougier" <notifications@github.com>
Pour : "ReScience/submissions" <submissions@noreply.github.com>
Cc : "Benoît Girard" <benoit.girard@isir.upmc.fr>, "Mention" <mention@noreply.github.com>
Objet : [ReScience/submissions] [Re] A Neurodynamical Model for Working Memory (#8)
Date : lun., oct. 28, 2019 10:37
@benoit-girard Could you edit this submission? 

&mdash;You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 
[ 
{ 
"@context": "http://schema.org", 
"@type": "EmailMessage", 
"potentialAction": { 
"@type": "ViewAction", 
"target": "https://github.com/ReScience/submissions/issues/8?email_source=notifications\u0026email_token=ADDFACU2KSAWQQ4NXSIDLR3QQ2XGHA5CNFSM4JESBKM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECMIJRQ#issuecomment-546866374", 
"url": "https://github.com/ReScience/submissions/issues/8?email_source=notifications\u0026email_token=ADDFACU2KSAWQQ4NXSIDLR3QQ2XGHA5CNFSM4JESBKM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECMIJRQ#issuecomment-546866374", 
"name": "View Issue" 
}, 
"description": "View this Issue on GitHub", 
"publisher": { 
"@type": "Organization", 
"name": "GitHub", 
"url": "https://github.com" 
} 
} 
]

**Comment by benoit-girard** [comment]
I have to check how the new review process works (and find reviewers...). Give me some time to do that.

**Comment by benoit-girard** [comment]
@neuronalX & @cJarvers : can you review this paper?

**Comment by benoit-girard** [comment]
Oh, I just saw that @cJarvers has been asked very recently for another review. Maybe I should ask someone else.
@Vahidrostami you think you could review this paper?

**Comment by Vahidrostami** [comment]
@benoit-girard I'd be happy to review this.

**Comment by neuronalX** [comment]
@benoit-girard 
I would be very happy to review this paper ...
but "unfortunately" I know way too much the authors! (one is my PhD student)

**Comment by neuronalX** [comment]
@benoit-girard You could ask Pierre Enel, who did a review previously, but I could not find his github account.

**Comment by benoit-girard** [comment]
@pietromarchesi would you like to review this submission to ReScience?

**Comment by rougier** [comment]
@benoit-girard Yes, because most editors forgot to fill it and it was only useful at the end when actually publish the paper.

**Comment by benoit-girard** [comment]
@cJarvers would you like to review this submission to ReScience?

**Comment by rougier** [comment]
🛎 Gentle reminder

**Comment by pietromarchesi** [comment]
Yes, and apologies for the late reply.

**Comment by rougier** [comment]
@benoit-girard @pietromarchesi @Vahidrostami Gentle reminder for the review...

**Comment by Vahidrostami** [comment]
@rougier @benoit-girard Sorry for the delay. I will try to finish it by the end of next week

**Comment by pietromarchesi** [comment]
@rougier @benoit-girard Same!

**Comment by Vahidrostami** [comment]
# Review: replication of "A Neurodynamical Model for Working Memory" by Pascanu and Jaeger

## General comments
In this manuscript, the authors provide a Python implementation of the working memory (WM) model, originally published by Pascanu and Jaeger. They verify the conclusion of the original publication on a bracket level parsing task using two different datasets (FreeMono and Incosolata fonts). The authors of the current manuscript did not have access to the exact font dataset used in the original publication, therefore, they can only qualitatively confirm the successful reproduction of the original article.

The manuscript is well written and focuses on the main results of the original publication. Although the authors did not have access to the exact font used in the original publication, they have demonstrated that their implementation of the WM model successfully accomplishes the task on two types of datasets with a reasonable error, not that different from the original publication. I find the manuscript suitable for publication in Rescience if it addresses the following few fairly minor concerns.


## Article comments
1- The first paragraph of page 6 is a bit confusing. The original paper uses FreeMono, FreeMono Bold, FreeMono Italic and FreeMono Bold Italic of Gimp 2.3.6 while the current paper (first sentence on page 6) states that the original paper uses (FreeMono classic, oblique, bold and bold oblique of Gimp 2.3.6). Could you please clarify exactly what fonts did you use and the differences between those fonts and the original publication?  Furthermore, could the difference in the performance using Freemono be explained by the difference between italic and oblique that have been used in the original paper and the current paper respectively?

2- Different types of errors indicated in Table 3 show a big difference between Freemono and Inconsolata. However, the average error rate is not that different between them. Is it correct?

3- Minor: Page 6, second sentence: a period missing at the end of the sentence

## Code comments
I could not find a clear package dependency list in the repo. When I ran the code I got the error for lacking some packages on my machine (e.g freetype-py, etc). It will be helpful to have a list of dependencies with their versions.
Apart from that, I could run the code smoothly and I found the code readability quite good and understandable (I have to mention that I did not go through the code line-by-line). The implementation is provided as a stand-alone repository which is well-structured and in addition, it follows what the authors describe in the manuscript.

**Comment by benoit-girard** [comment]
@Vahidrostami : thanks a lot for your first review feedback
@theoboraud : can you address the questions raised by @Vahidrostami 
@pietromarchesi : a gentle reminder...

**Comment by anthony-strock** [comment]
@Vahidrostami Thank you for the review, we'll address your questions and remarks by the end of the week.

**Comment by benoit-girard** [comment]
@pietromarchesi : are you still onboard for this review?

**Comment by rougier** [comment]
Any progress ?

**Comment by benoit-girard** [comment]
@pietromarchesi : in case you cannot do it, can you just tell me, so that I can search for another reviewer?

**Comment by cJarvers** [comment]
@benoit-girard: in case @pietromarchesi decides not to review after all, I'd be happy to act as a reviewer.
Sorry for the very late reply. I missed that you asked me again on November 6.

**Comment by benoit-girard** [comment]
@cJarvers Thanks a lot for your proposal: yes go on please. 
I was considering doing the review myself, but with the lockdown and kids at home I didn't find time to do that yet..

**Comment by cJarvers** [comment]
# Review of replication of "A neurodynamical model for working memory" by Pascanu and Jaeger

This review is based on commit https://github.com/theoboraud/ESN/commit/8e4fdb64f5edd7d8b1613143a9e8a9a5cb3b5b18

The version of the original article I read was [this preprint](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.718.3306&rep=rep1&type=pdf), so if any of the comparisons to the original article I draw are wrong / different in the final published version, apologies for that.


## Replication

All results from the paper are replicated to a reasonable degree.

The main difference are the error rates with the FreeMono font. In general, I find it curious that the error rates differ that much between the different fonts. Do you have a hypothesis why this might be? If so, it may be good to discuss this in the paper.

The points for the different working memory states in Figure 4 are clustered much more clearly than in the original article and span a much larger range. This is more of a quantitative than a qualitative difference, but maybe it would still be good if you would comment on it briefly.


## Reproducibility

As reviewer 1 noted already, there is not clear dependency list. In order to make the code reproducible, an exact list of the versions of dependencies used should be given, for example by freezing the local environment with `pip freeze > requirements.txt`

I ran the code on Manjaro Linux, using Python 3.8.2, numpy 1.18.3, tqdm 4.45.0, pilow 7.1.2, freetype-py 2.1.0, scipy 1.4.1, matplotlib 3.2.1, and scikit-learn 0.22.2.

When running the code with `main.py` a seed is randomly generated based on the runtime. This means the results are different on each run, which makes an exact reproduction of the results difficult. Since a seed can be specified as a command-line argument, it would be sufficient to write down which seed was used to generate the results in the paper. Please add this information somewhere.

As far as I can see, replicating the whole paper requires running `main.py` twice with different input arguments and `PCA.py` once. It would be nice to have one scripts that runs the whole analysis at once, optimally with the same seed values as used in the replication.


## Clarity of code

In general, I think the code is quite clear and readable.

Some minor points:

- In `ESN.py`, the arguments named in the docstring for the constructor do not match the actual arguments.
- In `ESN.py`, both the constructor and the `set_seed` function check if the module is run in script mode and, if so, use command-line arguments instead of the arguments passed to the function. First of all, I think that's not a good idea (since you have a bit of scripts code at the end of the file anyway, you call the functions with the appropriate arguments, so you could just use these). Secondly, both try to use `sys.argv[1]`, but once as the font name and once as the random seed. That should be resolved.
- `ESN.py` has code residues in lines 9-11, 209-210, 273-274, 286-287, 424-426, 450-451, and 571-575. These could be removed. You also still have comments reading "to change" in lines 356 and 369. If you still want to change something there, please do it before the final publication, otherwise remove these comments. 
- In `alphascii.py` lines 56-59, the Roboto font is defined, but trying to use this would throw an error due to lines 66-71. You should either take this font out or make it work.
- `alphascii.py` contains commented-out alternative versions of `convert_sequence_to_img` (lines 166-206) and `compute_target_outputs` (lines 414-447). There is also dead code in lines 305-306 and 327-329. These should be removed.
- In the function `random_sequence` in `alphascii.py`, I don't understand why the while-loop (line 134) is needed. Unless I'm mistaken, `char` gets a value in any branch of the following conditions, so the loop will only run for one iteration. Maybe this can be shortened?
- I found the `convert_sequence_to_img` function in `alphascii.py` a bit hard to follow. Maybe you could add a few more comments, particularly in the first and second pass loops?


## Clarity of article

I found the article to be quite clear and well readable.

Nevertheless, there are a few small things which I believe could improve the clarity of the article:

As Reviewer 1 already noted, it is not quite clear what the differences between the fonts in the original publication and the current replication is. I believe the only difference is that you did not verify whether you version of FreeMono is the same as the one used in Gimp 2.3.6 and that you used oblique instead of italic?

It may be useful to reorder equations 2-4 such that 4 comes directly after 2, since these two relate to each other, but not to 3. This could be done by switching 2 and 3 or by switching 3 and 4.

In section 2.6, subsection "Warm up in Principle Component Analysis", I'm not sure what "but not to perform the PCA" means. Maybe you can clarify whether these points were included in the PCA calculation.

In the analysis of the working memory errors, the original article stated that there was no case in which the WM representation increased or decreased by more than one, which shows that the network learned the "semantics" of the memory correctly. Unless I missed it, the replication article does not state whether this was the case in the replication too. Maybe you could check this and include it in the text?


## Misc

There were a few more small issues I noticed:

- The input sequence in Table 2 seems to be incorrect, with the Markov chain sometimes advancing by 1 letter, sometimes by 2. I thought the step size should always be the same. Am I missing something?
- In Table 4, the number of times the counter increased / decreased for the character "]" is specifies as 7.2 ± 6.5, which seems to be different from the publication, where the values are 0.05 ± 0.03 and 6.0 ± 5.4, respectively.

I believe I found some minor errors and typos (I'm not a native speaker, so I may be wrong):

- In much of the article, tenses are mixed (e.g., both simple past and past perfect for original article). Settling on one form would aid readability.
- In some places, there is a doubling of plural forms in compound words (such as "inputs units", "weights matrices", "non-zeros connections"). I think only the second word should be plural.
- in section 2.4, "at all time" should be "at all times" 
- in section 2.5, "input nits" should be "input units"
- in section 2.5, "every units" should be "all units"
- in section 2.6, "the choice we made" should be "the choices we made"
- in section 2.6, subsection "Font", a full stop seems to be missing between the words "font" and "However".


## Summary

Most of these issues are rather minor. The most important points, which I think must be fixed before accepting this replication are:

- the missing dependency list
- noting the random seed used to generate the results
- discussing the small differences from the original results in some more detail

**Comment by pietromarchesi** [comment]
Apologies everyone, I have been terribly unresponsive. I find myself too busy at the moment to address this properly. Very sorry to have delayed the process, please continue without me.

**Comment by benoit-girard** [comment]
That's OK @pietromarchesi , we have been saved by @cJarvers 

@theoboraud we are really sorry for the unusually long time for the evaluation of your work. You may now proceed to answer the reviewers' comments and requests.

**Comment by rougier** [comment]
CCing to co-author @anthony-strock

**Comment by benoit-girard** [comment]
@cJarvers : do you think you could finish your review for the 22nd of May?

**Comment by cJarvers** [comment]
@benoit-girard: I already posted my review above (https://github.com/ReScience/submissions/issues/8#issuecomment-619608039). I forgot to tag you in that comment, sorry about that.

**Comment by theoboraud** [comment]
Hello all,
Thank you for your reviews!We are starting to address seriously the issues you pointed out in them. We come back to you at the end of the week when it's done.
Best regards,
Theophile Boraud
    Le jeudi 14 mai 2020 à 17:25:46 UTC+2, Christian Jarvers <notifications@github.com> a écrit :  
 
 


@benoit-girard: I already posted my review above (#8 (comment)). I forgot to tag you in that comment, sorry about that.

**Comment by benoit-girard** [comment]
@cJarvers Sorry for my inattention, and thanks a lot for delivering the review.

**Comment by cJarvers** [comment]
No problem and you're welcome :smile:

**Comment by benoit-girard** [comment]
@theoboraud is everything processing smoothly?

**Comment by rougier** [comment]
@benoit-girard @theoboraud @anthony-strock Gentle reminder

**Comment by benoit-girard** [comment]
@theoboraud @anthony-strock Cascading Gentle reminder

**Comment by theoboraud** [comment]
@benoit-girard @rougier @Vahidrostami @cJarvers I am deeply sorry for this very late answer. I told @anthony-strock I would take care of it since he was working on his thesis, so I am the only one to blame, and I thought I already sent the corrections to you in July, and never checked back after. I deeply apologized for this unprofessional behavior and hope it did not create additional issues.

I answered every issue mentioned both by @Vahidrostami and @cJarvers, replying to their own report, which you can find below:

# Review by @Vahidrostami
> # Review: replication of "A Neurodynamical Model for Working Memory" by Pascanu and Jaeger
> ## General comments
> In this manuscript, the authors provide a Python implementation of the working memory (WM) model, originally published by Pascanu and Jaeger. They verify the conclusion of the original publication on a bracket level parsing task using two different datasets (FreeMono and Incosolata fonts). The authors of the current manuscript did not have access to the exact font dataset used in the original publication, therefore, they can only qualitatively confirm the successful reproduction of the original article.
>
> The manuscript is well written and focuses on the main results of the original publication. Although the authors did not have access to the exact font used in the original publication, they have demonstrated that their implementation of the WM model successfully accomplishes the task on two types of datasets with a reasonable error, not that different from the original publication. I find the manuscript suitable for publication in Rescience if it addresses the following few fairly minor concerns.
>
> ## Article comments
> 1- The first paragraph of page 6 is a bit confusing. The original paper uses FreeMono, FreeMono Bold, FreeMono Italic and FreeMono Bold Italic of Gimp 2.3.6 while the current paper (first sentence on page 6) states that the original paper uses (FreeMono classic, oblique, bold and bold oblique of Gimp 2.3.6). Could you please clarify exactly what fonts did you use and the differences between those fonts and the original publication? Furthermore, could the difference in the performance using Freemono be explained by the difference between italic and oblique that have been used in the original paper and the current paper respectively?
>
* The mention of FreeMono Italic and FreeMono Bold Italic is a mistake, the FreeMono fonts we used being Oblique. The typo has been corrected both in the article but also in the code. Furthermore, you can access the fonts used for the replication by clicking on their name via an hyperlink.
>
> 2- Different types of errors indicated in Table 3 show a big difference between Freemono and Inconsolata. However, the average error rate is not that different between them. Is it correct?
>
* Yes it is correct, the average error rate over the 30 runs is only for the prediction of the output units, while the tables show the errors for the WM-units. We tried to keep the same form as in the original article, for clarity purposes, even if it does not appear as clear as we could expect.
>
> 3- Minor: Page 6, second sentence: a period missing at the end of the sentence
>
* Typo now corrected.
>
> ## Code comments
> I could not find a clear package dependency list in the repo. When I ran the code I got the error for lacking some packages on my machine (e.g freetype-py, etc). It will be helpful to have a list of dependencies with their versions.
> Apart from that, I could run the code smoothly and I found the code readability quite good and understandable (I have to mention that I did not go through the code line-by-line). The implementation is provided as a stand-alone repository which is well-structured and in addition, it follows what the authors describe in the manuscript.
* We now included the package dependency in the repository in respond to this review.



# Review by @cJarvers 
> # Review of replication of "A neurodynamical model for working memory" by Pascanu and Jaeger
> This review is based on commit [theoboraud/ESN@8e4fdb6](https://github.com/theoboraud/ESN/commit/8e4fdb64f5edd7d8b1613143a9e8a9a5cb3b5b18)
>
> The version of the original article I read was [this preprint](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.718.3306&rep=rep1&type=pdf), so if any of the comparisons to the original article I draw are wrong / different in the final published version, apologies for that.
>
> ## Replication
> All results from the paper are replicated to a reasonable degree.
>
> The main difference are the error rates with the FreeMono font. In general, I find it curious that the error rates differ that much between the different fonts. Do you have a hypothesis why this might be? If so, it may be good to discuss this in the paper.
>
* As you suggested, we added in the conclusion the fact that we did not used the same tools for input generation (language, algorithm from string to image, ASCII alphabet, noise settings...), therefore implying differences between their results and ours.
>
> The points for the different working memory states in Figure 4 are clustered much more clearly than in the original article and span a much larger range. This is more of a quantitative than a qualitative difference, but maybe it would still be good if you would comment on it briefly.
>
* We now added this analysis in the comment section of Figure 4.
>
> ## Reproducibility
> As reviewer 1 noted already, there is not clear dependency list. In order to make the code reproducible, an exact list of the versions of dependencies used should be given, for example by freezing the local environment with `pip freeze > requirements.txt`
>
> I ran the code on Manjaro Linux, using Python 3.8.2, numpy 1.18.3, tqdm 4.45.0, pilow 7.1.2, freetype-py 2.1.0, scipy 1.4.1, matplotlib 3.2.1, and scikit-learn 0.22.2.
>
* We added the file `requirements.txt` to the repository.
>
> When running the code with `main.py` a seed is randomly generated based on the runtime. This means the results are different on each run, which makes an exact reproduction of the results difficult. Since a seed can be specified as a command-line argument, it would be sufficient to write down which seed was used to generate the results in the paper. Please add this information somewhere.
>
* We added the seed in section 3.1 Network, as footnotes.
>
> As far as I can see, replicating the whole paper requires running `main.py` twice with different input arguments and `PCA.py` once. It would be nice to have one scripts that runs the whole analysis at once, optimally with the same seed values as used in the replication.
>
* The script `article_compute_results.py` and `article_load_results.py` have been added to the repository in order to only launch them to obtain the same results as in the article. You can obtain more details on the README on GitHub.
>
> ## Clarity of code
> In general, I think the code is quite clear and readable.
>
> Some minor points:
>
> * In `ESN.py`, the arguments named in the docstring for the constructor do not match the actual arguments.
> * In `ESN.py`, both the constructor and the `set_seed` function check if the module is run in script mode and, if so, use command-line arguments instead of the arguments passed to the function. First of all, I think that's not a good idea (since you have a bit of scripts code at the end of the file anyway, you call the functions with the appropriate arguments, so you could just use these). Secondly, both try to use `sys.argv[1]`, but once as the font name and once as the random seed. That should be resolved.
> * `ESN.py` has code residues in lines 9-11, 209-210, 273-274, 286-287, 424-426, 450-451, and 571-575. These could be removed. You also still have comments reading "to change" in lines 356 and 369. If you still want to change something there, please do it before the final publication, otherwise remove these comments.
> * In `alphascii.py` lines 56-59, the Roboto font is defined, but trying to use this would throw an error due to lines 66-71. You should either take this font out or make it work.
> * `alphascii.py` contains commented-out alternative versions of `convert_sequence_to_img` (lines 166-206) and `compute_target_outputs` (lines 414-447). There is also dead code in lines 305-306 and 327-329. These should be removed.
> * In the function `random_sequence` in `alphascii.py`, I don't understand why the while-loop (line 134) is needed. Unless I'm mistaken, `char` gets a value in any branch of the following conditions, so the loop will only run for one iteration. Maybe this can be shortened?
>
* All these issues have been solved, thank you for your in-depth review.
>
> * I found the `convert_sequence_to_img` function in `alphascii.py` a bit hard to follow. Maybe you could add a few more comments, particularly in the first and second pass loops?
>
* This issue would be more difficult to resolve, since this portion of the code is quite hard for us to understand as well after so much time. **If it still needs to be solved before publishing the article, we will jump into the issue to make it clearer.**
>
> ## Clarity of article
> I found the article to be quite clear and well readable.
>
> Nevertheless, there are a few small things which I believe could improve the clarity of the article:
>
> As Reviewer 1 already noted, it is not quite clear what the differences between the fonts in the original publication and the current replication is. I believe the only difference is that you did not verify whether you version of FreeMono is the same as the one used in Gimp 2.3.6 and that you used oblique instead of italic?
>
* We used a FreeMono font that can be found by clicking on the hyperlink in the text, which is not the Gimp 2.3.6 since we were not able to find it. Saying italic was a mistake, it was the oblique version since the beginning, so we corrected that typo in the article and the code.
>
> It may be useful to reorder equations 2-4 such that 4 comes directly after 2, since these two relate to each other, but not to 3. This could be done by switching 2 and 3 or by switching 3 and 4.
>
* Equation 3 is used in equation 2, that's why we used that order. **Do you think we should still reorder them?**
>
> In section 2.6, subsection "Warm up in Principle Component Analysis", I'm not sure what "but not to perform the PCA" means. Maybe you can clarify whether these points were included in the PCA calculation.
>
* We corrected that section to make it clearer.
>
> In the analysis of the working memory errors, the original article stated that there was no case in which the WM representation increased or decreased by more than one, which shows that the network learned the "semantics" of the memory correctly. Unless I missed it, the replication article does not state whether this was the case in the replication too. Maybe you could check this and include it in the text?
>
* We added a paragraph at the end of section 3.1 Network to highlight the same results as expected in the original article.
>
> ## Misc
> There were a few more small issues I noticed:
>
> * The input sequence in Table 2 seems to be incorrect, with the Markov chain sometimes advancing by 1 letter, sometimes by 2. I thought the step size should always be the same. Am I missing something?
>
* The Markov Chain should advance most of the time by 1 character on the ASCII alphabet (alphascii) if the bracket level is at 0, 2 characters if the bracket level is at 1, and so on, with a maximum bracket level of 6. **Should we specify in more details the process in section 2.2 Input generation ?**
>
> * In Table 4, the number of times the counter increased / decreased for the character "]" is specifies as 7.2 ± 6.5, which seems to be different from the publication, where the values are 0.05 ± 0.03 and 6.0 ± 5.4, respectively.
>
* This typo has been corrected thanks to your meticulous review.
>
> I believe I found some minor errors and typos (I'm not a native speaker, so I may be wrong):
>
> * In much of the article, tenses are mixed (e.g., both simple past and past perfect for original article). Settling on one form would aid readability.
> * In some places, there is a doubling of plural forms in compound words (such as "inputs units", "weights matrices", "non-zeros connections"). I think only the second word should be plural.
> * in section 2.4, "at all time" should be "at all times"
> * in section 2.5, "input nits" should be "input units"
> * in section 2.5, "every units" should be "all units"
> * in section 2.6, "the choice we made" should be "the choices we made"
> * in section 2.6, subsection "Font", a full stop seems to be missing between the words "font" and "However".
>
* All these errors and typos have been corrected, and we chose to use simple past for the whole article.
>
> ## Summary
> Most of these issues are rather minor. The most important points, which I think must be fixed before accepting this replication are:
>
> * the missing dependency list
> * noting the random seed used to generate the results
> * discussing the small differences from the original results in some more detail


I apologize again for answering your reviews so late, even more so considering the amount of time invested on this article. I will be as responsive as possible for any question or request you may have.
Thank you for your help and your time.

**Comment by cJarvers** [comment]
@theoboraud, thanks for the detailed answer. Don't worry about the delay - I think given all that's been going on this year, it's quite normal that some mix-ups occur.
I've looked through the changes you made to the code and manuscript and I think you've addressed all my concerns adequately. Concerning the three open questions:

- More comments on `convert_sequence_to_img` would have been nice, but I don't think they're necessary for publication. If it would be too much extra work to dig back into the code, leave it be.
- Looking at the order of equations 2-4 again, especially with your explanation, I'm not quite sure what my original problem was. The way you do it is fine.
- Rereading your explanations in section 2.2, I also understand that the input sequence in Table 2 is correct. Again, I'm not sure what my original problem was - I must have misread something. My fault entirely, your explanations are fine.

While running the updated code, I ran into two issues:

- When I try to install all the packages from `requirements.txt`, I get an error that seems to be related to the numpy version. I strongly suspect that this is a problem on my computer, but since I found no quick way to resolve it, I'd like to make sure that it's really on my end. Could you please set up a clean virtualenv and run `pip install -r requirements.txt` to confirm that it does not throw any errors?
- In the scripts `article_compute_results.py` and `article_load_results.py`, you import a lot of python packages, but then you only use `os` to run another python instance. I think you could remove all the other imports.

It would be nice if you could check / fix those two things. Otherwise, I'm happy with the current status and recommend publication, @benoit-girard

**Comment by theoboraud** [comment]
@cJarvers thank you for your (very quick) answer and your understanding, I really appreciate. 

> * More comments on `convert_sequence_to_img` would have been nice, but I don't think they're necessary for publication. If it would be too much extra work to dig back into the code, leave it be.
I think it would be too much effort indeed. We coded that part a long time ago with the only goal of obtaining results, and did not comment anything afterwards. If anyone really thinks it would be a game-breaker for the publication, we will definitely work it through, but since you told us it would only be a minor issue we did not jumped into it for now. Don't hesitate to ask us if any of you feels it is necessary.
> * Looking at the order of equations 2-4 again, especially with your explanation, I'm not quite sure what my original problem was. The way you do it is fine.
> * Rereading your explanations in section 2.2, I also understand that the input sequence in Table 2 is correct. Again, I'm not sure what my original problem was - I must have misread something. My fault entirely, your explanations are fine.
> 
I'm sure it was hard to invest so much time trying to look for errors or mistakes, and given the length and amount of informations in the article, it would have been inevitable.
>
> While running the updated code, I ran into two issues:
> 
> * When I try to install all the packages from `requirements.txt`, I get an error that seems to be related to the numpy version. I strongly suspect that this is a problem on my computer, but since I found no quick way to resolve it, I'd like to make sure that it's really on my end. Could you please set up a clean virtualenv and run `pip install -r requirements.txt` to confirm that it does not throw any errors?
> * In the scripts `article_compute_results.py` and `article_load_results.py`, you import a lot of python packages, but then you only use `os` to run another python instance. I think you could remove all the other imports.
> 
> It would be nice if you could check / fix those two things. Otherwise, I'm happy with the current status and recommend publication, @benoit-girard

Those two issues should be fixed, I updated them both on the repo, could you try again? 

Many thanks for your answer and your help!

**Comment by cJarvers** [comment]
@theoboraud great, that fixed everything.
@benoit-girard, in my opinion everything is fine for publication now.

**Comment by Vahidrostami** [comment]
@theoboraud thanks for addressing my comments and don't worry about the delay. I think we all felt the strong nonlinearity of time in 2020! 
@benoit-girard I am happy with the paper for publication as it is now.

**Comment by benoit-girard** [comment]
Dear colleagues, sorry for my lack of activity here.
Based on @Vahidrostami and @cJarvers positive feedback, I am happy to declare the paper accepted for publication in ReScience C!

I will handle the publishing process as fast as possible.

@rougier Am I correct, when assuming that I should claim issue 7, volume 1, number 1 for this paper? (I have doubts about the numbering procedure)

**Comment by rougier** [comment]
Yes, correct!

**Comment by benoit-girard** [comment]
@theoboraud : can you replace your metadata.yaml with the updated one:

```
# To be filled by the author(s) at the time of submission
# -------------------------------------------------------

# Title of the article:
#  - For a successful replication, it shoudl be prefixed with "[Re]"
#  - For a failed replication, it should be prefixed with "[¬Re]"
#  - For other article types, no instruction (but please, not too long)
title: "[Re] A Neurodynamical Model for Working Memory"

# List of authors with name, orcid number, email and affiliation
# Affiliation "*" means contact author
authors:
  - name: Theophile Boraud
    orcid: 0000-0003-0388-0392
    email: theoboraud@outlook.com
    affiliations: 1,4,* # * is for contact author

  - name: Anthony Strock
    orcid: 0000-0002-6725-561X
    email: Anthony.Strock@inria.fr
    affiliations: 1,2,3

# List of affiliations with code (corresponding to author affiliations), name
# and address. You can also use these affiliations to add text such as "Equal
# contributions" as name (with no address).
affiliations:
  - code:    1
    name:    INRIA Bordeaux Sud-Ouest
    address: Bordeaux, France

  - code:    2
    name:    LaBRI, Université de Bordeaux, Institut Polytechnique de Bordeaux,
             Centre National de la Recherche Scientifique, UMR 5800
    address: Talence, France

  - code:    3
    name:    Institut des Maladies Neurodégénératives, Université  de Bordeaux,
             Centre National de la Recherche Scientifique, UMR 5293
    address: Bordeaux, France

  - code:    4
    name:    Department of Computer Science, University of Warwick
    address: Coventry, United Kingdoms


# List of keywords (adding the programming language might be a good idea)
keywords: Recurrent Neural Networks, Echo State Networks, Working Memory

# Code URL and DOI (url is mandatory for replication, doi after acceptance)
# You can get a DOI for your code from Zenodo,
#   see https://guides.github.com/activities/citable-code/
code:
  - url: https://github.com/theoboraud/JaegerESN
  - doi:

# Date URL and DOI (optional if no data)
data:
  - url:
  - doi:

# Information about the original article that has been replicated
replication:
 - cite: Pascanu, R., & Jaeger, H. (2011). A neurodynamical model for working memory. Neural networks, 24(2), 199-207. # Full textual citation
 - bib:  # Bibtex key (if any) in your bibliography file
 - url:  https://www.sciencedirect.com/science/article/abs/pii/S0893608010001899 # URL to the PDF, try to link to a non-paywall version
 - doi:  10.1016/j.neunet.2010.10.003 # Regular digital object identifier

# Don't forget to surround abstract with double quotes
abstract: "Neurodynamical models of working memory (WM) should provide mechanisms
for storing, maintaining, retrieving, and deleting information. Raznan Pascanu and
Herbert Jaeger have suggested that memory states correspond, intuitively in terms of
nonlinear dynamics, to attractors in an input-driven system, giving a simple WM model
training all performance modes into a Recurrent Neural Network (RNN) of the Echo State
Network (ESN) type.
In this replication, we reproduced this WM model in Python in order to see wether or
not these observations could be observed on a slightly different model made from scratch."

# Bibliography file (yours)
bibliography: bibliography.bib

# Type of the article
# Type can be:
#  * Editorial
#  * Letter
#  * Replication
type: Replication

# Scientific domain of the article (e.g. Computational Neuroscience)
#  (one domain only & try to be not overly specific)
domain: Computational Neuroscience

# Coding language (main one only if several)
language: Python


# To be filled by the author(s) after acceptance
# -----------------------------------------------------------------------------

# For example, the URL of the GitHub issue where review actually occured
review:
  - url: https://github.com/ReScience/submissions/issues/8

contributors:
  - name: Benoît Girard
    orcid: 0000-0002-8117-7064
    role: editor
  - name: Vahid Rostami
    orcid: 0000-0002-3851-0220
    role: reviewer
  - name: Christian Jarvers
    orcid: 0000-0003-0062-9776
    role: reviewer

# This information will be provided by the editor
dates:
  - received: October 24, 2019
  - accepted: March 8, 2021
  - published: March 9, 2021

# This information will be provided by the editor
article:
  - number: 1 # Article number will be automatically assigned during publication
  - doi: 10.5281/zenodo.4590961   # DOI from Zenodo
  - url: https://zenodo.org/record/4590961/files/article.pdf   # Final PDF URL (Zenodo or rescience website?)

# This information will be provided by the editor
journal:
  - name:   "ReScience C"
  - issn:   2430-3658
  - volume: 7
  - issue:  1
```
